#adCategory
application_setting_adCategory_create:
    path:     /create
    defaults: { _controller: SettingBundle:AdCategory:create }
application_setting_adCategory_list:
    path:     /list
    defaults: { _controller: SettingBundle:AdCategory:list}
application_setting_adCategory_edit:
    path:     /{id}/edit
    defaults: { _controller: SettingBundle:AdCategory:edit}
#
application_setting_adCategory_filter:
    path:     /filter
    defaults: { _controller: SettingBundle:AdCategory:filter}
application_setting_adCategory_disable:
    path:     /{id}/disable
    defaults: { _controller: SettingBundle:AdCategory:disable }
application_setting_adCategory_enable:
    path:     /{id}/enable
    defaults: { _controller: SettingBundle:AdCategory:enable }
application_setting_adCategory_delete:
    path:     /{id}/delete
    defaults: { _controller: SettingBundle:AdCategory:delete }