services:
#    claim.example:
#        class: ClaimBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    application_claim_service:
        class:   ClaimBundle\Services\ClaimService
        arguments: ['@doctrine.orm.entity_manager']