#ad_homepage:
#    path:     /
#    defaults: { _controller: AdBundle:Default:index }
#adCategory

application_ad_list:
    path:     /list
    defaults: { _controller: AdBundle:Ad:list}
application_ad_edit:
    path:     /{id}/edit
    defaults: { _controller:  AdBundle:Ad:edit}
#
application_ad_filter:
    path:     /filter
    defaults: { _controller: AdBundle:Ad:filter}
application_ad_disable:
    path:     /{id}/disable
    defaults: { _controller: AdBundle:Ad:disable }
application_ad_enable:
    path:     /{id}/enable
    defaults: { _controller: AdBundle:Ad:enable }
application_ad_delete:
    path:     /{id}/delete
    defaults: { _controller: AdBundle:Ad:delete }