application_setting_adCategory:
    resource: "@SettingBundle/Resources/config/routing/adCategory.yml"
    prefix:   /adCategory
application_setting_claim:
    resource: "@SettingBundle/Resources/config/routing/claim.yml"
    prefix:   /claimCategory
