services:
#    setting.example:
#        class: SettingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    application_setting_service:
        class:   SettingBundle\Services\SettingService
        arguments: ['@doctrine.orm.entity_manager']
